### ISSUE TITLE
Missing License, Cannot be used

### ISSUE THREAD

**Issue by WelpSTudent** [shedaniel/SmoothScrollingEverywhere#18]

**Comment by vizthex123** [comment]
same here, quite annoying. I'm on the Forge version.

**Comment by JetpackRescue** [comment]
IT'S STILL A PROBLEM. YOUR MOD DOESN'T WORK ON 1.16.5

**Comment by shedaniel** [comment]
Duplicate of https://github.com/shedaniel/SmoothScrollingEverywhere/issues/14
