### ISSUE TITLE
Add option to disable animations

### ISSUE THREAD

**Issue by juliand665** [shedaniel/SmoothScrollingEverywhere#7]
When scrolling with certain trackpads (e.g. apple's), they seem to send a lot more scroll events than your animation code can handle, resulting in jumpy scrolling. In fact, I think they send so many events that you shouldn't need to animate anything at all.

So an easy fix would be to add an option to disable animations entirely while keeping the overscrolling feature. Of course, it would be even better if it would just always work, so I'd still have smooth scrolling with my external mouse's wheel.

**Comment by shedaniel** [comment]
There is a config for that, you can keep overscrolling with animations disabled.

**Comment by juliand665** [comment]
Oh damn, can't believe I missed that. I guess I should have looked into the cloth-config2 folder rather than just looking for something named smooth scrolling.

I set `scrollDuration1=1` and that seems to work pretty well. It still doesn't feel as smooth as I hoped, and it overscrolls way too far, but I think those are problems I'd best look at solving in my own fork or something.

**Comment by shedaniel** [comment]
You can also access the smooth scrolling everywhere's config by using modmenu, also the correct way to disable animations is to set the easing method to NONE.

**Comment by juliand665** [comment]
Nice, that makes more sense. Can confirm those parts work :p
